### PR TITLE
14 login

### LINKED ISSUE #14: As a user I want to login on trashradar
An unauthenticated user can login on TrashRadar and receive an authentication token.
FRONTEND
- [ ] Go to `/login` and view the login form
- [ ] Show any error for invalid submissions
- [ ] If the user is logged in, store the authentication token on LocalStorage and redirect to /home
- [ ] If the user is logged in and go to /login, redirect to home

BACKEND
**Acceptance criteria**
1. Given a user post a JSON object to `/auth/login/` 
      1.  When the user is authenticated.
             1. Then there will be an HTTP response with status 200 OK.
             2. The response will contain JSON object with the account details.
             3. The response will have the authentication token.
             4. The user is authenticated
   2.  When the user is unauthenticated.
             1. Then there will be an HTTP response with status 200 OK.
             2. The response will contain JSON object with the account details.
             3. The response will have the authentication token.
             4. The user is authenticated

### LINKED ISSUE #15: As a user I want to logout on trashradar
An authenticated user can logout on Trashradar and clean the authentication token.

**Acceptance criteria**
1. Given an user posts a json object to `/auth/logout/` 
      1.  When the user is authenticated.
             1. Then there will be an HTTP response with status 204 No Content.
             2. The response will contains an empty JSON object 
             3. The response will clean the authentication token.
             4. The user is unauthenticated

   2.  When the user is unauthenticated.
             1. Then there will be an HTTP response with status 204 No Content.
             2. The response will contains an empty JSON object 
             3. The response will clean the authentication token.
             4. The user is unauthenticated

### LINKED ISSUE #28: Create a Service to communicate with the back end.
The service should provide an easy way of interacting with the back end using GET, POST, UPDATE and DELETE requests.

### PR DESCRIPTION
**Pull request by Klemensas**
Closes https://github.com/spry-group/trashradar-api/issues/14, closes https://github.com/spry-group/trashradar-api/issues/28, closes https://github.com/spry-group/trashradar-api/issues/15

This adds basic login functionality.

> If the user is logged in and go to /login, redirect to home

Skipped this one, I think it's better to implement this when doing https://github.com/spry-group/trashradar-api/issues/56

Reused stuff from tn-admin here. Had to refactor django service as it wasn't flexible enough.

### CODE REVIEW

**Comment by marton987** [comment]
Impressive PR @Klemensas, thanks for covering a lot of things here. I think you have the fix for https://github.com/spry-group/trashradar-api/issues/28 and https://github.com/spry-group/trashradar-api/issues/15 too; if that's correct, do you mind update the description to close all those issues?

**Comment by Klemensas** [comment]
Updated

**Comment by marton987** [comment]
I'm getting:
```
ERROR in /Users/martin_jft/Projects/trashradar/trashradar/src/app/services/auth/auth.service.ts (50,12): Type 'Subscription' is not assignable to type 'Observable<any>'.
  Property '_isScalar' is missing in type 'Subscription'.)
webpack: Failed to compile.
```

**Review by marton987 — APPROVED** [review]
Looks good to me!

**Pull request merged**
